spring.application.name=skillbridge

spring.datasource.url=jdbc:postgresql://localhost:5432/skillbridge
spring.datasource.username=postgres
spring.datasource.password=anshuman101

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=a7d3f8e2c5b1a0e9f8d7c6b5a4f3e2d1c0b9a8f7e6d5c4b3a2f1e0d9c8b7a6f5e4d3c2b1a0f9e8d7c6b5a4f3e2d1c0b9a8f7e6d5c4b3a2f1e0d9c8b7a6f5e4d3
jwt.expiration=3600000